version: '2'
services:
  api:
    build: api/
    environment:
    - FAM_DEBUG=1
    ports:
      - "8081:8081"
    networks:
      fam_net:
        ipv4_address: 10.0.0.2
  timescale:
    image: timescale/timescaledb:latest-pg14
    environment:
      - POSTGRES_PASSWORD=fam_never_in_production_please
    ports:
      - "5432:5432"
    networks:
      fam_net:
        ipv4_address: 10.0.0.4
networks:
  fam_net:
    ipam:
      config:
        - subnet: 10.0.0.0/8
          gateway: 10.0.0.1