version: '2'
services:
  api:
    build: api/
    ports:
      - "8081:8081"
    networks:
      fam_net:
        ipv4_address: 10.0.0.2
  influx:
    image: influxdb:2.3
    environment:
      - DOCKER_INFLUXDB_INIT_USERNAME=fam_root
      - DOCKER_INFLUXDB_INIT_USERNAME=fam_never_in_production_please
      - DOCKER_INFLUXDB_INIT_ORG=falco_alert_manager
      - DOCKER_INFLUXDB_INIT_BUCKET=events
      - DOCKER_INFLUXDB_INIT_RETENTION=1w # 1 week of data retention just in case...
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=fam_token_never_in_production_please
    ports:
      - "8086:8086"
    networks:
      fam_net:
        ipv4_address: 10.0.0.3
networks:
  fam_net:
    ipam:
      config:
        - subnet: 10.0.0.0/8
          gateway: 10.0.0.1