from golang:1.18

WORKDIR /usr/src/app

COPY go.mod go.sum ./
RUN go mod download && go mod verify

# move everything into usr src app
COPY . .
RUN go build -v -o fam_api ./...
RUN ln -sf /usr/src/app/fam_api /usr/local/bin/fam_api

CMD ["fam_api"]